// projects/whats-new-kit/src/lib/whats-new-kit.component.ts
import {Component, Input, OnInit, ViewEncapsulation} from '@angular/core';
import {ModalController} from "@ionic/angular";
import {Storage} from "@capacitor/storage";

export type WhatsNewKitFeature = {
  icon: {
    name: string;
    color?: string;
  },
  title: string;
  text: string;
};

type ShowConfig = {
  /**
   * Declare if it can be show on web
   */
  appVersion: string,
  /**
   * Skip patch version 0.0.x
   */
  skipPatchVersion?: boolean,
  /**
   * Skip minor version 0.x.x
   */
  skipMinorVersion?: boolean
}

@Component({
  selector: 'aw3sm-whats-new-kit',
  templateUrl: 'whats-new-kit.component.html',
  styleUrls: [
    'whats-new-kit.component.scss'
  ],
  encapsulation: ViewEncapsulation.None
})
export class WhatsNewKitComponent implements OnInit {

  constructor(
    private modalController: ModalController,
  ) {
  }

  static appVersion?: string;

  @Input() title!: string;

  @Input() buttons!: {
    more?: {
      title: string,
      color?: string,
      handler?: () => string;
    };
    continue: {
      title: string,
      color?: string,
      handler?: () => string;
    };
  };

  @Input() features: WhatsNewKitFeature[] = [];

  /**
   * Compare versions & check if WNK can be shown
   *
   * @return Promise<boolean>
   */
  static async canShow(config: ShowConfig): Promise<boolean> {
    WhatsNewKitComponent.appVersion = config.appVersion;
    const {value} = await Storage.get({
      key: 'wnk_app_saved_version',
    });
    if (value) {
      const v1 = value.split('.');
      const v2 = WhatsNewKitComponent.appVersion.split('.');

      // minor update
      if (config.skipMinorVersion) {
        if (v1[0] === v2[0]) {
          return false;
        } else {
          return value < WhatsNewKitComponent.appVersion;
        }
      }

      // path update
      if (config.skipPatchVersion) {
        if (v1[0] === v2[0] && v1[1] === v2[1]) {
          return false;
        } else {
          return value < WhatsNewKitComponent.appVersion;
        }
      }

      // major update
      return value < WhatsNewKitComponent.appVersion;
    } else {
      // new install app
      return true;
    }
  }

  ngOnInit() {
  }

  async continue() {
    // @ts-ignore
    this.buttons.continue.handler?.call('continue-handler');

    // check version and save it if needed
    await Storage.set({
      key: 'wnk_app_saved_version',
      value: WhatsNewKitComponent.appVersion ?? '0',
    })

    await this.modalController.dismiss();
  }

  more() {
    // @ts-ignore
    this.buttons.more?.handler?.call('more-handler');
  }
}

<ion-content class="aw3sm-wnk ion-padding-vertical">
  <div class="ion-padding-horizontal margin-vertical">
    <ion-text class="ion-text-center">
      <h1 class="large-text"><strong [innerHTML]="title">{{title}}</strong></h1>
    </ion-text>
  </div>

  <ion-list>
    <ion-item *ngFor="let feature of features" lines="none">
      <ion-label class="ion-text-wrap">
        <ion-row>
          <ion-col size="auto" class="ion-align-self-center">
            <ion-icon [name]="feature.icon.name" [color]="feature.icon?.color"
                      class="large-icon"></ion-icon>
          </ion-col>
          <ion-col>
            <ion-text>
              <strong [innerHTML]="feature.title"></strong>
            </ion-text>
            <div [innerHTML]="feature.text">
            </div>
          </ion-col>
        </ion-row>

      </ion-label>
    </ion-item>
  </ion-list>
</ion-content>
<ion-footer class="ion-padding aw3sm-wnk">

  <div class="ion-text-center" *ngIf="buttons.more?.title">
    <ion-button (click)="more()" fill="clear" [color]="buttons.more?.color">{{buttons.more?.title}}</ion-button>
  </div>
  <ion-button (click)="continue()" expand="block" [color]="buttons.continue?.color" class="ion-margin-bottom">{{buttons.continue.title}}</ion-button>
</ion-footer>

// src/components/whats-new-kit/whats-new-kit.tsx
import {Component, Host, h, Prop} from '@stencil/core';
import {modalController} from "@ionic/core";


export type WhatsNewKitFeature = {
    icon: {
        name: string;
        color?: string;
    },
    title: string;
    text: string;
};

@Component({
    tag: 'whats-new-kit',
    styleUrl: 'whats-new-kit.scss',
    shadow: false,
})
export class WhatsNewKit {

    static appVersion?: string;

    @Prop() title: string;

    @Prop() buttons: {
        more?: {
            title: string,
            color?: string,
            handler?: () => string;
        };
        continue: {
            title: string,
            color?: string,
            handler?: () => string;
        };
    };

    @Prop() features: WhatsNewKitFeature[] = [];

    async continue() {
        this.buttons.continue.handler?.call('continue-handler');

        // check version and save it if needed
        // TODO: capacitor storage
        /*await Storage.set({
            key: 'wnk_app_saved_version',
            value: WhatsNewKit.appVersion ?? '0',
        })*/

        await modalController.dismiss();
    }

    more() {
        this.buttons.more?.handler?.call('more-handler');
    }

    render() {
        return (
            <Host>
                <ion-content class="aw3sm-wnk ion-padding-vertical">
                    <div class="ion-padding-horizontal margin-vertical">
                        <ion-text class="ion-text-center">
                            <h1 class="large-text"><strong innerHTML={this.title}></strong></h1>
                        </ion-text>
                    </div>
                    <ion-list>
                         {this.features.map((feature) => (
                            <ion-item lines="none">
                                <ion-label class="ion-text-wrap">
                                    <ion-row>
                                        <ion-col size="auto" class="ion-align-self-center">
                                            <ion-icon name={feature.icon.name} color={feature.icon?.color}
                                                      class="large-icon"></ion-icon>
                                        </ion-col>
                                        <ion-col>
                                            <ion-text>
                                                <strong innerHTML={feature.title}></strong>
                                            </ion-text>
                                            <div innerHTML={feature.text}>
                                            </div>
                                        </ion-col>
                                    </ion-row>
                                </ion-label>
                            </ion-item>
                        ))}
                    </ion-list>
                </ion-content>
                <ion-footer class="ion-padding aw3sm-wnk">
                    {this.buttons.more?.title
                        ? <div class="ion-text-center">
                            <ion-button onClick={this.more} fill="clear"
                                        color={this.buttons.more?.color}>{this.buttons.more?.title}</ion-button>
                        </div> : null}
                    <ion-button onClick={this.continue} expand="block" color={this.buttons.continue?.color ?? 'primary'}
                                class={'margin-bottom'}>{this.buttons.continue.title ?? 'zavřít'}</ion-button>
                </ion-footer>
            </Host>
        );
    }

}
